POST {{url}}/employer/task?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{employer_authenticated_token}}

{
    "title": "asdasd",
    "description": "asdasdasd",
    "hour_rate": 100,
    "required_tasker_number": 1,
    "required_tasker_gender": "male",
    "latitude": 10.2,
    "longitude": 10.2,
    "task_type": "one_time",
    "one_time_start_date": "2020-07-24",
    "one_time_start_time": "21:00",
    "one_time_end_time": "23:00"
}

###


POST http://saah.local/api/employer/task?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNmM5NzdlOTZmZTMzZmVkYzAwOWQ5NjVjODkwMmQwZjU4MGNlN2VjYjU3ZTEyNzI3NzAwZWJjNDA5ZTBmNDIzNTU2MGZjMmM0NmI4OGRkOTgiLCJpYXQiOjE1ODAzODYwNDMsIm5iZiI6MTU4MDM4NjA0MywiZXhwIjoxNzY5Nzc0ODQyLCJzdWIiOiIxOSIsInNjb3BlcyI6WyJlbXBsb3llciJdfQ.lCwwNKYOjqs6Q9KnyG5q4RFyIzv-YxGwHlc5b7pplRlA6hBsSpzfUDMjIfo_sy-PEjsWAEsHte32wENZMWzZibtQ-IhIYjJSjkzOGxp0Pidxn2wGJeGhpwODMHueJ4_EMOl6QlguvVZZpMnIblpihXMtvX7TWDeaIZkw2cS3iFrjx4oplcB0lGVsUrWjQnfOlWSNOoL2s2I-Pt0VXYc08oSFoWQbhcJ1pYBBTlDxcElOOeagW4Nq_S_GLBefaUsVuZ6samUdL32DtaeBZk2yvrFpF5qZKKRbaHXSHeGWqb0TiB2IUGJFVAWgmt_ut9driL3H2g1klrC3Jbds34CZc142wi_6T2UaX2IRkwXTxAHlp5GzSxwjnbqLBGgQa-dCHKzZ1AnIQh5ClRD7I2CnbbisgNMawUgRiQfYHa2hWI_1hbFfza7IJ41suvYcXoVJIdhxH-rmpLNSck_LJNPtOsaWzL_gi6NF2iRSOrolhgwaFurxK94MMR_-pzdpS_P6qMtqLFK5z6R90_gq_x4gW4WlOtq_p0RqfOCMFRSHlDtdrC0HxQqfhExnCVgXS2r01coCRU-gQ86CDzJa8GKyqMyA5rrPwwl7Q3_k9cAnPw0_iXTm1pp3_oaugyvYVHDbwBPQTE3FCcOjyU7Hjad7quqLJO81oY7DDTfbMrq-z2s

{
    "title": "asdasd",
    "description": "asdasdasd",
    "hour_rate": 100,
    "required_tasker_number": 2,
    "required_tasker_gender": "male",
    "city_id": 1,
    "task_type": "repeated",
    "repeated_days": [
        {
            "weekday": "sunday",
            "start_time": "10:23:12",
            "duration": 4
        },
        {
            "weekday": "saturday",
            "start_time": "10:23:12",
            "duration": 4
        }
    ],
    "repeated_start_date": "2020-02-19",
    "repeated_end_date": "2020-02-19"
}

###



POST {{url}}/employer/task?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{employer_authenticated_token_253_510001000}}

{
    "title": "asdasd",
    "description": "asdasdasd",
    "hour_rate": 100,
    "required_tasker_number": 2,
    "required_tasker_gender": "male",
    "city_id": 1,
    "task_type": "continued",
    "continued_start_at": "2020-10-12 08:00:00",
    "continued_daily_duration": 10,
    "continued_end_date": "2020-10-14",
    "latitude": 10.1,
    "longitude": 10.1
}

###

GET {{url}}/employer/task?XDEBUG_SESSION_START=PHPSTORM&status[]=sending&status[]=canceled
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{employer_authenticated_token}}

###

GET {{url}}/employer/task/116?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{employer_authenticated_token}}

###

PUT {{url}}/api/employer/task/21/cancel?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{employer_authenticated_token}}

###

GET {{url}}/employer/task
Accept: application/json
Authorization: Bearer {{employer_authenticated_token_zoza}}
###

GET {{url}}/employer/task/143
Accept: application/json
Authorization: Bearer {{employer_authenticated_token_215_560009000}}

###

PUT {{url}}/employer/task/181/pay?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{employer_authenticated_token_69}}

{
    "payment_type": "online",
    "credit_card_id": 22
}
