### register employer
POST http://saah.local/api/tasker/password/forget?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json
Accept: application/json

{
    "email": "amir.modarresis@yahoo.com"
}

###

