GET http://saah.local/api/tasker/skill?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNjI2YzY0YzVlMjM5NTBkYjg1ZWUwMWRmYmUwMjE0NGQ4OGU0ODQzN2VlMjQ3NmE1MzQzNTJlYzNhZWRjNWNiZDc3MGRjNDVmZWRlY2FjZWMiLCJpYXQiOjE1ODAzODkwMDcsIm5iZiI6MTU4MDM4OTAwNywiZXhwIjoxNzY5Nzc3ODA3LCJzdWIiOiIyMiIsInNjb3BlcyI6WyJ0YXNrZXIiXX0.oIPYokdGEXIxQ4rIRphZC3PYL8l0yabhPVHKognyJgDOjrZSKBPAc-hX8sbG9uK4nnltdVcO_WpIgOb4Ux_UGguVx1hf51i8O-LoWcx7VO2EhWRktdsuIwpkC4k1Um4HxcsKzOgIWO-OaB-t2kzoDNt2Kc3Ek9dQKXls3DOz2S_6PNXXMxCax9HIsG3n4EV7xgFI3UmGLY-99nmmD-1G4B-CUXz5oiOLMpxm4J1OAr68SIqGtt2PnKw8f-NBNdMW_JEtq7Bo5Lb1G5fJU310v1fBkYccde860bApjl6vr3iIYVb1RNlbDzNHyt3fviZ_GEyXMyNOKdcPbuZVoLoNVecSdBIWn6bEB2yUaxH36bwr_ie7UMxXjeAgzL9AwwuzMovNj5YDxLPRCQbjjSbg2ILNcQHXD5LICbOm1seaZqhwx_nWUR86g0z7YcMc8MwPGjNCTVJkWFN8wZK-ACtzc_NDSHlT6dt-l-5s1RrPIA5xMkHEXu3PeicDMdodde2a8K1O8vovoLr8GUuADETKekVi0vXx8ht5uQxEsHl8-l5VNHz9ISIMUFwsGI52i7b1vqu-EP5Yc8TS6FBHaeuMc30zc2daV1-xNv7zIgqGKRElA7HMlLbYko9QDBmdrSWZhh6Jbv1cigFfnoZH-Hh8n1LGkJPiMqscVqDmOeOTTQ4

###
